import Head from 'next/head';
import Image from 'next/image';
import Layout from '@/components/layout';

export default function Home() {
	return (
		<Layout home>
			<Head>
				<title>Moment Log</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					as='style'
					href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css'
				/>
			</Head>
			<div>Home</div>
		</Layout>
	);
}
