import Head from 'next/head';
import Layout from '@/components/layout';
import MyPage from './mypage';
import { useSession } from 'next-auth/react';

export default function Home() {
	const { data: session, status } = useSession();
	console.log('status: ', status);
	console.log('session: ', session);

	return (
		<Layout home>
			<Head>
				<title>Moment Log</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					as='style'
					href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css'
				/>
			</Head>
			{session ? <MyPage /> : <div>로그인 안한 홈</div>}
		</Layout>
	);
}
